name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Zsh and Poetry
      run: |
        sudo apt update
        sudo apt install -y zsh python3-pip
        pip install "poetry==2.1.1"
        
    - name: Run tests
      run: make test-verbose
      
    - name: Run lint
      run: make lint